version: '3'

services:

  classification:
    build:
      context: ./classification
      args:
        APPLICATION_PORT: 8001
        JMX_PORT: 18001
        DEBUG_PORT: 28001
    container_name: classification
    image: classification
    environment:
      - APPLICATION_PORT=8001
      - JMX_PORT=18001
      - DEBUG_PORT=28001
      - MEMORY_OPTS=-Xmx64m
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8001:8001"
      - "18001:18001"
      - "28001:28001"
  classification-reactive:
    build:
      context: ./classification-reactive
      args:
        APPLICATION_PORT: 8010
        JMX_PORT: 18010
        DEBUG_PORT: 28010
    container_name: classificationreactive
    image: classificationreactive
    environment:
      - APPLICATION_PORT=8010
      - JMX_PORT=18001
      - DEBUG_PORT=28001
      - MEMORY_OPTS=-Xmx64m
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8010:8010"
      - "18010:18010"
      - "28010:28010"

  claims:
    build:
      context: ./claims
      args:
        APPLICATION_PORT: 8002
        JMX_PORT: 18002
        DEBUG_PORT: 28002
    container_name: claims
    image: claims
    environment:
      - APPLICATION_PORT=8002
      - JMX_PORT=18002
      - DEBUG_PORT=28002
      - MEMORY_OPTS=-Xmx64m
      - CLAIMS_SIMULATEDPROCESSINGTIMEMILLIS=1000
    ports:
      - "8002:8002"
      - "18002:18002"
      - "28002:28002"

  communication:
    build:
      context: ./communication
      args:
        APPLICATION_PORT: 8003
        JMX_PORT: 18003
        DEBUG_PORT: 28003
    container_name: communication
    image: communication
    environment:
      - APPLICATION_PORT=8003
      - JMX_PORT=18003
      - DEBUG_PORT=28003
      - MEMORY_OPTS=-Xmx64m
      - COMMUNICATION_SIMULATEDPROCESSINGTIMEMILLIS=1000
    ports:
      - "8003:8003"
      - "18003:18003"
      - "28003:28003"

  feedback:
    build:
      context: ./feedback
      args:
        APPLICATION_PORT: 8004
        JMX_PORT: 18004
        DEBUG_PORT: 28004
    container_name: feedback
    image: feedback
    environment:
      - APPLICATION_PORT=8004
      - JMX_PORT=18004
      - DEBUG_PORT=28004
      - MEMORY_OPTS=-Xmx64m
      - FEEDBACK_SIMULATEDPROCESSINGTIMEMILLIS=1000
    ports:
      - "8004:8004"
      - "18004:18004"
      - "28004:28004"

  payments:
    build:
      context: ./payments
      args:
        APPLICATION_PORT: 8005
        JMX_PORT: 18005
        DEBUG_PORT: 28005
    container_name: payments
    image: payments
    environment:
      - APPLICATION_PORT=8005
      - JMX_PORT=18005
      - DEBUG_PORT=28005
      - MEMORY_OPTS=-Xmx64m
      - PAYMENTS_SIMULATEDPROCESSINGTIMEMILLIS=1000
    ports:
      - "8005:8005"
      - "18005:18005"
      - "28005:28005"

  prometheus:
    build: ./prometheus
    container_name: prometheus
    image: prometheus
    ports:
      - "9090:9090"

  grafana:
    build: ./grafana
    container_name: grafana
    image: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - "3000:3000"
