# Documentation: https://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'classification'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['classification:8001']