FROM grafana/grafana
ADD datasource.yml /etc/grafana/provisioning/datasources/datasource.yml
ADD dashboard.yml /etc/grafana/provisioning/dashboards/dashboard.yml
ADD enrichers_monitoring_dashboard.json /etc/grafana/provisioning/dashboards/enrichers_monitoring_dashboard.json
