{
 "title": "Enrichers Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Outgoing HTTP request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average HTTP request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_sum[5m]) / rate(http_client_requests_seconds_count[5m])) by (clientName)",
     "legendFormat": "{{clientName}}"
    }
   ]
  },
  {
   "title": "HTTP requests rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{status=~\"2..\"}[5m]))",
     "legendFormat": "2XX OK"
    },
    {
     "expr": "sum(rate(http_client_requests_seconds_count{status!~\"2..\"}[5m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "Number of errors over last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count{status!~\"2..\"}[5m])) by (clientName)",
     "legendFormat": "{{clientName}} ERROR"
    }
   ]
  }
 ]
}